### ISSUE TITLE
lsnodecanister not valid on SV 8.1.3.5

### ISSUE THREAD

**Issue by robinsg** [IBM/SVCheck#3]
The 1.1 version now gets past lssystem but fails at:

2020-05-12 13:38:21,231 DEBUG:   Checking user superuser has appropiate role for command lsnodecanister
2020-05-12 13:38:21,231 DEBUG:   All groups can run lsnodecanister
2020-05-12 13:38:21,231 DEBUG:   Going to send command run lsnodecanister to API
2020-05-12 13:38:21,233 DEBUG:   Starting new HTTPS connection (1): 172.xxxx.yyyy.zzzz:7443
2020-05-12 13:38:21,390 DEBUG:   https://172.xxxx.yyyy.zzzz:7443 "POST /rest/lsnodecanister HTTP/1.1" 404 41
2020-05-12 13:38:21,391 ERROR:   Cannot run lsnodecanister to API

**Comment by bolinches** [comment]
8.1.3 was the first that introduced the API I have tested on 8.2.x clearly 8.1.3 does not implement all the API calls that were after introduced .... lsnodecanister is an important one that was not on 8.1.3 it seems to work on Storwize/Flashsystem and SVC for 8.2.x but clearly not on 8.1.3. I will be guessing you are running SVC?

**Comment by bolinches** [comment]
Well I decided that as u been the only one active to report stuff is fair you get it working. I changed lsnodecanister for lsnode now. That will work on 8.1.3 SVC but will fail on 8.1.3 Storwize. It will work on both 8.2 and 8.3. As 8.1.3 goes EOS end of this year I think I will just leave like that ....

**Comment by robinsg** [comment]
One last one from me with 8.1.3.5.

I ran again and had to comment out lssystemstats and lssystemip report_commands.

With these removed SVCheck executes OK against 8.1.3.5 on V7000.

**Comment by bolinches** [comment]
Thanks for checking. That is too much compromise. lssystemstats is very valuable to have on the report. I think I just check add to read me 8.2 is min version. I could add a check to fail if 8.1.3 but  i Leave like this I think. Thanks

**Comment by bolinches** [comment]
Updated readme to reflect the problems on 8.1.3
